export const icons = {
    autoTheme: 0,
    arrowBack: 1,
    brackets: 2,
    chevronBack: 3,
    autoThemeAlt: 4,
    email: 5,
    cv: 6,
    languages: 7,
    github: 8,
    web: 9,
    phone: 10,
    darkTheme: 11,
    design: 12,
    lightTheme: 13,
    call: 14,
    desktop: 15,
    externalLink: 16,
    chevronDown: 17,
    print: 18
};